#!/usr/bin/env python3
"""Generate src/moonbit/compiler/lib_sources_gen.mbt from the TypeScript
repository's src/lib/*.d.ts files.

Only the JavaScript-only libraries are embedded (es5, es2015..es2025 chains,
esnext.*, decorators). DOM / webworker / scripthost libs are intentionally
excluded (too large; the checker keeps its name whitelist as a fallback for
those). The ".full" wrapper libs are also excluded (they only reference dom).

Usage: python3 tools/gen_embedded_libs.py [path-to-typescript-repo]
"""
import os
import sys

TS_REPO = sys.argv[1] if len(sys.argv) > 1 else "/Users/sriky/Personal/typescript/typescript-repo"
LIB_DIR = os.path.join(TS_REPO, "src", "lib")
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "moonbit", "compiler", "lib_sources_gen.mbt")

def included(name: str) -> bool:
    if name in ("libs.json", "README.md"):
        return False
    if not name.endswith(".d.ts"):
        return False
    base = name[:-len(".d.ts")]
    if base.startswith(("dom", "webworker", "scripthost")):
        return False
    if base.endswith(".full"):
        return False
    return True

libs = sorted(base[:-len(".d.ts")] for base in os.listdir(LIB_DIR) if included(base))

def mbt_ident(lib: str) -> str:
    return "lib_src_" + lib.replace(".", "_")

out = []
out.append("// GENERATED FILE - DO NOT EDIT.")
out.append("// Generated by tools/gen_embedded_libs.py from the TypeScript repository's")
out.append("// src/lib/*.d.ts files (JavaScript-only libs; dom/webworker/scripthost excluded).")
out.append("// Regenerate with: python3 tools/gen_embedded_libs.py <path-to-typescript-repo>")
out.append("")
out.append("///|")
out.append("/// Names of all embedded standard-library files (without the lib. / .d.ts")
out.append("/// wrapping), e.g. \"es5\", \"es2015.promise\".")
out.append("pub fn embedded_lib_names() -> Array[String] {")
out.append("  [")
for lib in libs:
    out.append(f'    "{lib}",')
out.append("  ]")
out.append("}")
out.append("")
out.append("///|")
out.append("/// Raw .d.ts source text of an embedded standard-library file.")
out.append("pub fn embedded_lib_source(name : String) -> String? {")
out.append("  match name {")
for lib in libs:
    out.append(f'    "{lib}" => Some({mbt_ident(lib)}())')
out.append("    _ => None")
out.append("  }")
out.append("}")

for lib in libs:
    path = os.path.join(LIB_DIR, lib + ".d.ts")
    with open(path, encoding="utf-8") as f:
        text = f.read()
    out.append("")
    out.append("///|")
    out.append(f"fn {mbt_ident(lib)}() -> String {{")
    lines = text.split("\n")
    # Drop a trailing empty element from a final newline
    if lines and lines[-1] == "":
        lines.pop()
    for i, line in enumerate(lines):
        out.append("  #|" + line)
    out.append("}")

with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(out) + "\n")
print(f"Wrote {os.path.abspath(OUT)}: {len(libs)} libs, {sum(1 for _ in open(OUT))} lines")
